version: '3.0'
services:
  api:
    build: api
    ports:
      - 5000:5000
  database:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: voucher
      POSTGRES_USER: voucher
      POSTGRES_DB: voucher
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432